#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#commitlint -E HUSKY_GIT_PARAMS -g './config/git/commitlint.js'
#commitlint --env ./config/git/commitlint.js
commitlint --edit $2 --config ../typescript-definitive-guide/config/git/commitlint.js
